# Generated by Django 3.0.2 on 2020-05-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submiteval',
            name='begintDate',
            field=models.DateTimeField(),
        ),
    ]
