# Generated by Django 3.0.2 on 2020-05-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20200507_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submiteval',
            name='begintDate',
        ),
    ]
