# Generated by Django 2.2.7 on 2020-06-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_submiteval_begintdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='reponse2',
            fields=[
                ('idr', models.AutoField(primary_key=True, serialize=False)),
                ('idEtudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Etudiant')),
                ('id_quizs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.evaluation')),
                ('id_reponses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.reponse')),
            ],
        ),
    ]
