# Generated by Django 2.2.7 on 2020-06-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_reponse2'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('idEtt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Etudiant')),
            ],
        ),
    ]
